CREATE TABLE IF NOT EXISTS tv_show (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    genre VARCHAR(255),
    seasons INT
);

INSERT INTO tv_show (name, genre, seasons) VALUES
('Breaking Bad', 'Crime', 5),
('Game of Thrones', 'Fantasy', 8),
('Stranger Things', 'Sci-Fi', 4),
('The Crown', 'Drama', 4),
('The Mandalorian', 'Sci-Fi', 2);

